### ISSUE TITLE
プレイヤー

### ISSUE THREAD

**Issue by wain0622** [wain0622/Platoform#3]
- [x] キャラクター作成
- [x] 動かすプログラム
> Dで右へ、Aで左へ,スペースでジャンプ
- [x] ジャンプ
- [x] #5
上のタスクは優先順

**Comment by TakaoWing** [comment]
Addforceを使った移動方法
[参考サイト](https://qiita.com/yuki2006/items/a60fc92e033dddcb3a83)

**Comment by TakaoWing** [comment]
var text = "test" この場合，textはString型に自動になる
var text = 1 この場合，textはint型に自動になる
varはトランプのジョーカー的な役割がある

**Comment by TakaoWing** [comment]
rb.velocity 速度でxyzそれぞれの軸に対して存在する．
rb.velocity.magnitudeで速さを求めることができる．

**Comment by TakaoWing** [comment]
# ジャンプ機能

- [ ] bool型のisGround変数を作る
- [ ] 地面に触れたらisGroundをtrueにする
- [ ] ジャンプするとisGroundをfalseにする
- [ ] ジャンプはisGroundがtrueのときのみできる

**Comment by TakaoWing** [comment]
# アニメーションの設定

![参考サイト](https://wdkids.sakura.ne.jp/ex/?p=2791)

**Comment by wain0622** [comment]
@TakaoWing アニメーションをDLするときに位置を変えないようにするにはどうすればいいんでしたっけ？

**Comment by wain0622** [comment]
アニメーションに関しては今後直す。その際、またイシュー開く
